#!/bin/sh
### BEGIN INIT INFO
# Provides: spindown
# Required-Start: $syslog
# Required-Stop:  $syslog 
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: 
### END INIT INFO

case "$1" in
'start')
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_W1F0HZXN
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_W1F0LVB1
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_Z1F0EJ0L
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_Z1F0D9GD
	/etc/init.d/pd_check &
	;;
'stop')
	killall pd_check
	;;
'restart')
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_W1F0HZXN
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_W1F0LVB1
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_Z1F0EJ0L
	/sbin/hdparm -S 241 /dev/disk/by-id/ata-ST3000DM001-9YN166_Z1F0D9GD
	#/etc/init.d/pd_check &
	#$0 stop
	#$0 start
	;;	
*)
	echo "Usage: $0 { start | stop | restart}"
	;;
esac
exit 0
